spring.application.name=ControlaDados

# ===============================
# MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/ifam_dad_202601?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#api.cidade.url=http://10.100.34.116:8081/api/cidade
api.cidade.url=http://localhost:8081/api/cidade

# API EXTERNA - ESTADO
api.estado.url=http://10.100.34.113:8081/api/estado
server.port=8081